export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENTS = "INIT_INGREDIENTS";
export const SET_INGREDIENTS = "SET_INGREDIENTS";

export const START_PURCHASE = "START_PURCHASE";
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAILED = "PURCHASE_FAILED";

export const RETRIEVE_ORDERS = "RETRIEVE_ORDERS";
export const RETRIEVE_ORDERS_SUCCESS = "RETRIEVE_ORDERS_SUCCESS";
export const RETRIEVE_ORDERS_FAILED = "RETRIEVE_ORDERS_FAILED";

export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const CLEAR_LOGIN = "CLEAR_LOGIN";
